"""add srs tables

Revision ID: 015_add_srs_tables
Revises: 014_add_bkt_tables
Create Date: 2026-01-21 14:00:00.000000

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "015_add_srs_tables"
down_revision = "014_add_bkt_tables"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create srs_user_params table
    op.create_table(
        "srs_user_params",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("fsrs_version", sa.String(length=20), nullable=False, server_default="fsrs-6"),
        sa.Column(
            "weights_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Personalized FSRS weights (19 params for v6)",
        ),
        sa.Column(
            "desired_retention",
            sa.Float(),
            nullable=False,
            server_default="0.90",
            comment="Target retention probability",
        ),
        sa.Column(
            "n_review_logs",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Total review logs for this user",
        ),
        sa.Column(
            "last_trained_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Last time weights were trained",
        ),
        sa.Column(
            "metrics_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
            comment="Training metrics: logloss, brier, ece, val_size, etc.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        "idx_srs_user_params_last_trained", "srs_user_params", ["last_trained_at"], unique=False
    )
    op.create_index(
        "idx_srs_user_params_n_logs", "srs_user_params", ["n_review_logs"], unique=False
    )

    # Create srs_concept_state table
    op.create_table(
        "srs_concept_state",
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("concept_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("stability", sa.Float(), nullable=False, comment="Memory stability (days)"),
        sa.Column("difficulty", sa.Float(), nullable=False, comment="Item difficulty [0, 10]"),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "due_at", sa.DateTime(timezone=True), nullable=True, comment="Next review due date"
        ),
        sa.Column(
            "last_retrievability",
            sa.Float(),
            nullable=True,
            comment="Retrievability at last review [0, 1]",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "concept_id"),
    )
    op.create_index("idx_srs_concept_state_due_at", "srs_concept_state", ["due_at"], unique=False)
    op.create_index(
        "idx_srs_concept_state_user_concept",
        "srs_concept_state",
        ["user_id", "concept_id"],
        unique=False,
    )
    op.create_index(
        "idx_srs_concept_state_user_due", "srs_concept_state", ["user_id", "due_at"], unique=False
    )

    # Create srs_review_log table
    op.create_table(
        "srs_review_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("concept_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=False,
            comment="FSRS rating 1-4 (Again, Hard, Good, Easy)",
        ),
        sa.Column("correct", sa.Boolean(), nullable=False, comment="Whether answer was correct"),
        sa.Column("delta_days", sa.Float(), nullable=False, comment="Days since last review"),
        sa.Column(
            "time_spent_ms", sa.Integer(), nullable=True, comment="Time spent on question (ms)"
        ),
        sa.Column("change_count", sa.Integer(), nullable=True, comment="Number of answer changes"),
        sa.Column(
            "predicted_retrievability",
            sa.Float(),
            nullable=True,
            comment="Predicted retrievability at review time [0, 1]",
        ),
        sa.Column(
            "raw_attempt_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment="Source session_answer.id",
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment="Source test_session.id",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_srs_review_log_session", "srs_review_log", ["session_id"], unique=False)
    op.create_index(
        "idx_srs_review_log_user_concept_reviewed",
        "srs_review_log",
        ["user_id", "concept_id", "reviewed_at"],
        unique=False,
    )
    op.create_index(
        "idx_srs_review_log_user_reviewed",
        "srs_review_log",
        ["user_id", "reviewed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_srs_review_log_concept_id"), "srs_review_log", ["concept_id"], unique=False
    )
    op.create_index(
        op.f("ix_srs_review_log_reviewed_at"), "srs_review_log", ["reviewed_at"], unique=False
    )
    op.create_index(op.f("ix_srs_review_log_user_id"), "srs_review_log", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_srs_review_log_user_id"), table_name="srs_review_log")
    op.drop_index(op.f("ix_srs_review_log_reviewed_at"), table_name="srs_review_log")
    op.drop_index(op.f("ix_srs_review_log_concept_id"), table_name="srs_review_log")
    op.drop_index("idx_srs_review_log_user_reviewed", table_name="srs_review_log")
    op.drop_index("idx_srs_review_log_user_concept_reviewed", table_name="srs_review_log")
    op.drop_index("idx_srs_review_log_session", table_name="srs_review_log")
    op.drop_table("srs_review_log")
    op.drop_index("idx_srs_concept_state_user_due", table_name="srs_concept_state")
    op.drop_index("idx_srs_concept_state_user_concept", table_name="srs_concept_state")
    op.drop_index("idx_srs_concept_state_due_at", table_name="srs_concept_state")
    op.drop_table("srs_concept_state")
    op.drop_index("idx_srs_user_params_n_logs", table_name="srs_user_params")
    op.drop_index("idx_srs_user_params_last_trained", table_name="srs_user_params")
    op.drop_table("srs_user_params")
    # ### end Alembic commands ###
